import type { Component } from 'vue';
import PMCamera from '../components/modules/print/PMCamera.vue';
import PMFakeReceipt from '../components/modules/print/PMFakeReceipt.vue';
import PMLargeText from '../components/modules/print/PMLargeText.vue';
import PMSudoku from '../components/modules/print/PMSudoku.vue';
import PMTodoList from '../components/modules/print/PMTodoList.vue';
import PMUpload from '../components/modules/print/PMUpload.vue';
import PMWebsite from '../components/modules/print/PMWebsite.vue';

type ModuleInfo = {
  id: string;
  name: string;
  description: string;
  component: Component;
};

export const printModules: ModuleInfo[] = [
  {
    id: 'upload',
    name: 'Upload',
    component: PMUpload,
    description: 'Upload an image and print it',
  },
  {
    id: 'camera',
    name: 'Camera',
    component: PMCamera,
    description: 'Capture a photo using your camera and print it',
  },
  {
    id: 'large-text',
    name: 'Large Text',
    component: PMLargeText,
    description: 'Print large text, perfect for signs or labels',
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    component: PMSudoku,
    description: 'Generate and print a Sudoku puzzle',
  },
  {
    id: 'todo-list',
    name: 'Todo List',
    component: PMTodoList,
    description: 'Create and print a simple to-do list',
  },
  {
    id: 'fake-receipt',
    name: 'Fake Receipt',
    component: PMFakeReceipt,
    description: 'Print a fake receipt generated by AI',
  },
  {
    id: 'website',
    name: 'Website',
    component: PMWebsite,
    description: 'Is your website thermal-printer ready?',
  },
];

export type PrintModuleId = (typeof printModules)[number]['id'];
